23/11/20 (14:23:02) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:23:03) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:23:05) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:23:40) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:24:08) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/11/20 (14:24:19) | ERROR: 'update_ms'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 514, in <module>
    CONFIG: Config = Config(CONFIG_FILE)
  File "/usr/bin/bpytop", line 427, in __init__
    conf: Dict[str, Union[str, int, bool]] = self.load_config()
  File "/usr/bin/bpytop", line 493, in load_config
    if isinstance(new_config["update_ms"], int) and new_config["update_ms"] < 100:
KeyError: 'update_ms'
23/12/20 (15:06:01) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
24/12/20 (11:37:29) | ERROR: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1199, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/francois/.config/bpytop/themes'
24/12/20 (11:38:00) | ERROR: Input thread failed with exception: (5, 'Input/output error')
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 872, in _get_key
    input_key = ""
  File "/usr/bin/bpytop", line 665, in __exit__
    termios.tcsetattr(self.stream, termios.TCSANOW, self.original_stty)
termios.error: (5, 'Input/output error')
